### ISSUE TITLE
Membership testing

### ISSUE THREAD

**Issue by jsego** [drexlerd/general_policy#2]
What is the most efficient way to test whether a rule alredy exists in the policy?
Also, is there a way to create a rule then add it to the policy when building it?

**Comment by drexlerd** [comment]
Regarding the first question: why is this relevant? I think because you want to minimize policies? There is no canonical representation generated for a rule. 
Regarding the second question: just call add_rule and then build the rule. I implemented it like this because there is error checking dependent on the GeneralPolicyRoot that is shared across all features and rules made from a policy.

**Comment by jsego** [comment]
Both questions are related to avoid adding rule duplicates in the policy, or testing whether a rule already exists.

The problem of adding first a rule and then fill it is the assumption that the rule will be new, but this is not always the case. 
A way to solve this issue is by:
a) checking and removing in the GP framework rule duplicates, or
b) from the code that is using the "general policy" framework, testing whether a rule exists to avoid adding it to the policy.

For instance, we want to map a state transition (s,s') abstracted in the feature pool F, and add it to the policy as a rule, but this rule possibly exists in the policy. The way to check it now is by evaluating every feature in s and s', and then call to `compute_rules_with_satisfied_condition()`, and if there are rules that satisfy the transition, then the rule already exists; but that doesn't look a very efficient way to check rule duplicates.

**Comment by drexlerd** [comment]
Avoiding duplicates is always great. However, we will have to change the public API for this because this requires rules to be fully initialized before adding them to the policy.

**Comment by drexlerd** [comment]
API for a factory that will take care of uniqueness checking similar to the idea used in dlplan.

```cpp
/**
 * SyntacticElementFactory takes care of uniqueness among features, conditions, effects, rules, policies
 */
class SynacticElementFactory {
public:
    SynacticElementFactory();
    ~SynacticElementFactory();

    std::shared_ptr<GeneralPolicy> make_policy(
        std::vector<std::shared_ptr<Rule>>&& rules);

    std::shared_ptr<Rule> make_rule(
        std::vector<std::unique_ptr<BaseCondition>>&& conditions,
        std::vector<std::unique_ptr<BaseEffect>>&& effects);

    std::shared_ptr<Feature<bool>> make_boolean_feature();
    std::shared_ptr<Feature<int>> make_numerical_feature();

    std::shared_ptr<BaseCondition> make_b_pos_condition(std::shared_ptr<Feature<bool>> b);
    // ...
};
```
